- name: Ensure correct ownership for i-doit files
  ansible.builtin.file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
- name: make html dir executeable for apache2
  ansible.builtin.file:
    path: "/var/www/html"
    mode: '0755'
## For performance resasons we dont use the find module (as recommended by the
# official documentation)
- name: Ensure correct directory permissions
  ansible.builtin.command: "sudo find . -type d -name \\* -exec chmod 775 {} \\;"
  args:
    chdir: "/var/www/html"
- name: Ensure correct file permissions
  ansible.builtin.command: "sudo find . -type f -exec chmod 664 {} \\;"
  args:
    chdir: "/var/www/html"
