- name: Ensure correct ownership for i-doit files
  ansible.builtin.file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
- name: make html dir executeable for apache2
  ansible.builtin.file:
    path: "/var/www/html"
    chmod: 0755
- name: Ensure correct directory permissions
  ansible.builtin.find:
    paths: /var/www/html
    file_type: directory
  register: dirs
- name: Set directory permissions to 0755
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ dirs.files }}"
- name: Ensure correct file permissions
  ansible.builtin.find:
    paths: /var/www/html
    file_type: file
  register: files
- name: Set file permissions to 0644
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0644'
  loop: "{{ files.files }}"
