- name: Prepare all hosts for installation
  hosts: all
  vars:
    apt_pkgs:
      - "python3-pymysql"
      - "unzip"
      - "moreutils"
  tasks:
    - name: Update and Upgrade APT Packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install required APT Packages
      ansible.builtin.apt:
        pkg: "{{ apt_pkgs }}"
- name: Install MariaDB
  hosts: mariadb
  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        file: "vars/idoit.yml"
    - name: Install MariaDB
      ansible.builtin.import_role:
        name: r_mariadb
      vars:
        mariadb_bind_address: "0.0.0.0"
    - name: Create i-doit Database User with needed priviliges
      community.mysql.mysql_user:
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        name: "{{ idoit_db_user }}"
        password: "{{ idoit_db_user_password }}"
        host: "%"
        priv: "*.*:ALL,GRANT"
        state: present
- name: Install i-doit
  hosts: idoit
  vars:
  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        file: "vars/idoit.yml"
    - name: Install PHP and required PHP mods and packages
      ansible.builtin.import_role:
        name: r_php
    - name: Install Apache Server
      ansible.builtin.import_role:
        name: r_apache
    - name: Install i-doit
      ansible.builtin.import_role:
        name: r_idoit
        tasks_from: install.yml
- name: Restore i-doit backup
  hosts: mariadb
  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        file: "vars/idoit.yml"
    - name: Copy idoit backup file
      ansible.builtin.copy:
        src: "{{ idoit_backup_src }}"
        dest: /tmp
      when: "idoit_backup_src != ''"
    - name: Restore Data from Backup
      community.mysql.mysql_db:
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        name: all
        state: import
        target: "/tmp/{{ idoit_backup_src | basename }}"
      when: "idoit_backup_src != ''"
