- name: Update i-doit
  hosts: idoit
  vars:
    to_version: 36
  tasks:
    # TODO: Update von apache, php etc. braucht man weiterhin
    - name: "Update i-doit to {{ to_version }}"
      ansible.builtin.include_role:
        name: r_idoit
        tasks_from: update.yml
      vars:
        desired_version: "{{ to_version }}" 
