- name: Update i-doit
  hosts: idoit
  vars:
    versions:
      - 29
      - 30
      - 33
      - 34
      - 35
  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        file: "vars/idoit.yml"
    - name: "Update i-doit in the following order {{ versions }}"
      ansible.builtin.include_role:
        name: r_idoit
        tasks_from: update.yml
      vars:
        desired_version: "{{ item }}"
      loop: "{{ versions }}"
