- name: Update i-doit
  hosts: idoit
  vars:
    idoit_db_user_password: "{{ lookup('ansible.builtin.env', 'IDOIT_DB_USER_PASSWORD') or lookup('ansible.builtin.password', 'idoit_db_user_password.txt', length=32, chars=['ascii_letters']) }}"
    versions:
      - 29
      - 30
      - 33
      - 34
      - 35
  tasks:
    - name: "Update i-doit in the following order {{ versions }}"
      ansible.builtin.include_role:
        name: r_idoit
        tasks_from: update.yml
      vars:
        desired_version: "{{ item }}"
        db_host: "192.168.56.41"
        db_password: "{{ idoit_db_user_password }}"
      loop: "{{ versions }}"
