php_version: "8.3"
php_mods_conf_dest: "/etc/php/{{ php_version }}/mods-available/i-doit.ini"
php_fpm_conf_dest: "/etc/php/{{ php_version }}/fpm/i-doit.conf"
php_pkgs:
  - "php=2:{{ php_version }}+93ubuntu2"
  - "php-bcmath"
  - "php-cli"
  - "php-common"
  - "php-curl"
  - "php-fpm"
  - "php-gd"
  - "php-ldap"
  - "php-mbstring"
  - "php-memcached"
  - "php-mysql"
  - "php-opcache"
  - "php-pgsql"
  - "php-soap"
  - "php-xml"
  - "php-zip"
  - "memcached"
