- name: Install PHP and Required PHP packages
  ansible.builtin.apt:
    pkg: "{{ php_pkgs }}"
- name: Copy PHP Mods Config
  ansible.builtin.template:
    src: configs/php_mods.ini.j2
    dest: "{{ php_mods_conf_dest }}"
- name: Copy PHP FPM Config
  ansible.builtin.template:
    src: configs/php_fpm.conf.j2
    dest: "{{ php_fpm_conf_dest }}"
- name: Enable PHP mods
  ansible.builtin.command: sudo phpenmod i-doit memcached
- name: Ensure mysqli uses the correct socket path
  ansible.builtin.lineinfile:
    path: "/etc/php/{{ php_version }}/mods-available/mysqli.ini"
    line: "mysqli.default_socket = /var/run/mysqld/mysqld.sock"
    state: present
