- name: Install PHP and Required PHP packages
  ansible.builtin.apt:
    pkg: "{{ __php_pkgs }}"
- name: Copy PHP Mods Config
  ansible.builtin.template:
    src: templates/php_mods.ini.j2
    dest: "{{ __php_mods_conf_dest }}"
- name: Remove default PHP FPM Config to avoid Socket conflicts
  ansible.builtin.file:
    path: "{{ __php_default_fpm_pool_conf }}"
    state: absent
- name: Copy PHP FPM Config
  ansible.builtin.template:
    src: templates/php_fpm.conf.j2
    dest: "{{ __php_fpm_conf_dest }}"
- name: Enable PHP mods
  ansible.builtin.command: sudo phpenmod i-doit memcached
- name: Update Apache Site with new PHP Version
  ansible.builtin.include_role:
    name: r_apache
    tasks_from: php_update.yml
- name: Restart FPM Service
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted
    enabled: true
